### ISSUE TITLE
Q: Show Terms of Current Tab

### ISSUE THREAD

**Issue by juvander** [w8tcha/WatchersNET.TagCloud#1]
Hei

How is this supposed to work? For me showing nothing and using selected vocabulary brings everything from all sites using the selected vocabulary.

Also, based on the screenshots, is the release version up to date with sources? Settings do look a bit different on my side.

**Comment by w8tcha** [comment]
> How is this supposed to work? For me showing nothing and using selected vocabulary brings everything from all sites using the selected vocabulary.

Did you actually have any tags defined for the tab? i don#t really remember but i think dnn still don't have a way to define tags via the ui.

> Also, based on the screenshots, is the release version up to date with sources? Settings do look a bit different on my side.

The screen shots are outdated. I will update them when i have some time...

**Comment by juvander** [comment]
Ok so what this is supposed to do is to show tags assigned to tab, not from tags found on modules from that tab.

What I was thinking was how this https://dnnradtagcloud.codeplex.com was showing all tags found from specific tab. Seems that this one was using specific sql query to find those from the database.

Would be much useful this way.
