### ISSUE TITLE
Update repo to ensure use of commonly searched phrases for DNN extentions

### ISSUE THREAD

**Issue by david-poindexter** [w8tcha/WatchersNET.TagCloud#4]
For greater discoverability, I recommend the following:
- Use **DNN (formerly DotNetNuke)** in the repo **Description** instead of just **DNN**.
- Add, at minimum, the topics **dnn**, **dnncms** and **dotnetnuke** just below the repo **Description**.
- I'll submit a PR shortly to update the README file to add relevant keywords.

**Comment by w8tcha** [comment]
done
